# .github/dependabot.yml
version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 20
    groups:
      github-actions-dependencies:
        patterns:
          - '*'
    schedule:
      interval: "weekly"
      day: friday
      time: '04:00'
